### ISSUE TITLE
DDAD training sample

### ISSUE THREAD

**Issue by DongyangHuLi** [weiyithu/SurroundDepth#18]
作者你好，我尝试着用你的模型训练了一下。但是在DDAD数据集下的训练样本似乎只有12319，而不是12650。请问这是正常的吗？我统计了我所下载的DDAD数据集的图片数目，确保了它是完整的（99600）。请问你是否与nuscence数据集一样去除了静态帧？在你提供的index.pkl中只有16421张图片，另外的79张是人为去除了吗?为什么要这么做呢？
另外，关于模型测试，SurroundDepth是没有额外设置测试集吗？
期待您的回复！
祝好！

**Comment by weiyithu** [comment]
是正常的，因为ddad里有一些重复帧，就是有几个sequence的前几帧和另外几个sequence的后几帧是重合的，所以我们给去掉了。我们没有额外设置测试集。

**Comment by DongyangHuLi** [comment]
> 是正常的，因为ddad里有一些重复帧，就是有几个sequence的前几帧和另外几个sequence的后几帧是重合的，所以我们给去掉了。我们没有额外设置测试集。

好的，谢谢您的回复。还有一个关于训练的问题，我使用您的代码进行训练，发现中途会存在某个gpu利用率为0的情况：
![image](https://github.com/weiyithu/SurroundDepth/assets/116615779/b3aa573e-78ab-475e-b128-4d6b2a7ac306)
然后整个训练所需的时间就会被拉得很长。这有可能是什么引起的呢？希望您能给我一些提示或帮助。

**Comment by weiyithu** [comment]
这个我没有遇到过，会不会是某个样本有问题或者0号卡有问题？
