### ISSUE TITLE
不能复现论文结果

### ISSUE THREAD

**Issue by DongyangHuLi** [weiyithu/SurroundDepth#19]
作者您好，
        我尝试复现论文中在DDAD数据集的实验结果。但是在20个epoch中，最好的结果也达不到论文中所展示的结果。
在scale-ambiguous evaluation中，最好的结果如下:
all
 abs_rel     |   sq_rel    |     rmse   |   rmse_log |       a1   |       a2     |       a3 | 
&   0.208  &   3.474  &  12.536  &   0.309  &   0.720  &   0.886  &   0.944  \\
以下是论文的结果：
![image](https://github.com/weiyithu/SurroundDepth/assets/116615779/0331545a-5e51-44c1-a42c-8711363f2f0b)

**Comment by weiyithu** [comment]
您好，您可以从以下几个方面检查下：
1. 能否用我们给的预训练好的模型复现出精度，来验证下环境是否有问题。
2.  我们是取得最好的epoch的结果，不是最后一个epoch，epoch之间精度会有抖动。
3. 我们是用8卡训练的，每张卡batch size为1

**Comment by DongyangHuLi** [comment]
> 您好，您可以从以下几个方面检查下：
> 
> 1. 能否用我们给的预训练好的模型复现出精度，来验证下环境是否有问题。
> 2. 我们是取得最好的epoch的结果，不是最后一个epoch，epoch之间精度会有抖动。
> 3. 我们是用8卡训练的，每张卡batch size为1

感谢您的回复。根据您的建议，我使用预训练模型进行测试，结果似乎更加糟糕：
![image](https://github.com/weiyithu/SurroundDepth/assets/116615779/698b9017-0c6d-47b1-bb71-2c64c24ccbb4)
我的环境基本按照您所推荐的环境进行配置，除了CUDA版本已经更新到了12.0。另外，我想知道在第三点中，卡的数量也会对最终结果造成比较大的影响吗?

**Comment by DongyangHuLi** [comment]
> > 您好，您可以从以下几个方面检查下：
> > 
> > 1. 能否用我们给的预训练好的模型复现出精度，来验证下环境是否有问题。
> > 2. 我们是取得最好的epoch的结果，不是最后一个epoch，epoch之间精度会有抖动。
> > 3. 我们是用8卡训练的，每张卡batch size为1
> 
> 感谢您的回复。根据您的建议，我使用预训练模型进行测试，结果似乎更加糟糕： ![image](https://user-images.githubusercontent.com/116615779/245038790-698b9017-0c6d-47b1-bb71-2c64c24ccbb4.png) 我的环境基本按照您所推荐的环境进行配置，除了CUDA版本已经更新到了12.0。另外，我想知道在第三点中，卡的数量也会对最终结果造成比较大的影响吗?

我换了一台CUDA版本较低的机器，复现出了论文结果：
![image](https://github.com/weiyithu/SurroundDepth/assets/116615779/131eac2f-d4c0-4d42-8993-8a38def8783d)
