### ISSUE TITLE
About disp to depth 

### ISSUE THREAD

**Issue by GANWANSHUI** [weiyithu/SurroundDepth#8]
Hi， Thanks a lot for the nice work!

I have a basic question about the disp to depth as follows:

def disp_to_depth(disp, min_depth, max_depth):
    """Convert network's sigmoid output into depth prediction
    The formula for this conversion is given in the 'additional considerations'
    section of the paper.
    """
    min_disp = 1 / max_depth
    max_disp = 1 / min_depth
    scaled_disp = min_disp + (max_disp - min_disp) * disp  # 0~1  0.1~10
    depth = 1 / scaled_disp # 0.1~10
    return scaled_disp, depth

May I ask the reason that doing such an operation for depth rather than disp * max_depth?  Thanks a lot for your help!

**Comment by weiyithu** [comment]
This operation is from monodepth2. Actually, I have tried directly * max_depth and they have comarable performances.

**Comment by GANWANSHUI** [comment]
Hi， I have tried to use this disp* max_depth setting, but still does not work. May I have your Wechat for the detail about this setting? Thank you!

**Comment by weiyithu** [comment]
Here is my Wechat 18600500891.
